{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    gardener.cloud/purpose: machineclass
type: Opaque
data:
  user: {{ $machineClass.secret.ionosUser }}
  password: {{ $machineClass.secret.ionosPassword }}
  userData: {{ $machineClass.secret.userData | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
providerSpec:
  datacenterID: {{ $machineClass.datacenterID }}
  cluster: {{ $machineClass.cluster }}
  zone: {{ $machineClass.zone }}
  cores: {{ $machineClass.cores }}
  memory: {{ $machineClass.memory }}
  imageID: {{ $machineClass.imageID }}
  sshKey: {{ $machineClass.sshKey }}
  networkIDs:
    wan: {{ $machineClass.networkIDs.wan | quote }}
{{- if $machineClass.networkIDs.workers }}
    workers: {{ $machineClass.networkIDs.workers | quote }}
{{- end }}
{{- if $machineClass.floatingPoolID }}
  floatingPoolID: {{ $machineClass.floatingPoolID }}
{{- end }}
  volumeSize: {{ $machineClass.volumeSize }}
{{- if $machineClass.extraConfig }}
  extraConfig:
{{ toYaml $machineClass.extraConfig | indent 4 }}
{{- end }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
provider: ionosdriver//127.0.0.1:8080
{{- end }}
