apiVersion: v1
kind: ConfigMap
metadata:
  name: ionos-csi-controller-observability-config
  namespace: {{ .Release.Namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  dashboard_operators: |
    ionos-csi-controller-dashboard.json: |-
{{- .Files.Get "ionos-csi-controller-dashboard.json" | nindent 6 }}

  dashboard_users: |
    ionos-csi-controller-dashboard.json: |-
{{- .Files.Get "ionos-csi-controller-dashboard.json" | nindent 6 }}
