---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: cloud.ionos.com
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ionos-csi-controller
  namespace: {{ .Release.Namespace }}
labels:
  gardener.cloud/role: controlplane
  app: kubernetes
  role: csi-plugin-controller
spec:
  serviceName: ionos-csi-controller
  replicas: {{ .Values.replicas }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: ionos-csi-controller
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: controlplane
        app: ionos-csi-controller
        role: ionos-csi
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
    spec:
      automountServiceAccountToken: false
      containers:
        - name: csi-attacher
          image: {{ index .Values.images "csi-attacher" }}
          args:
          - "--timeout=300s"
          - "--csi-address=$(ADDRESS)"
          {{- if .Values.global.useTokenRequestor }}
          - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
          {{- else }}
          - --kubeconfig=/var/lib/csi-attacher/kubeconfig
          {{- end }}
          - "--leader-election"
          - "--leader-election-namespace=$(CSI_NAMESPACE)"
          env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: CSI_NAMESPACE
            value: kube-system
{{- if .Values.resources.attacher }}
          resources:
{{ toYaml .Values.resources.attacher | indent 12 }}
{{- end }}
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          {{- if .Values.global.useTokenRequestor }}
          - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
            name: kubeconfig-csi-attacher
            readOnly: true
          {{- else }}
          - name: csi-attacher
            mountPath: /var/lib/csi-attacher
          {{- end }}
{{- if .Values.resizerEnabled }}
        - name: csi-resizer
          image: {{ index .Values.images "csi-resizer" }}
          args:
          - "--csiTimeout=300s"
          - "--csi-address=$(ADDRESS)"
          {{- if .Values.global.useTokenRequestor }}
          - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
          {{- else }}
          - --kubeconfig=/var/lib/csi-resizer/kubeconfig
          {{- end }}
          - "--leader-election"
          - "--leader-election-namespace=$(CSI_NAMESPACE)"
          env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: CSI_NAMESPACE
            value: kube-system
{{- if .Values.resources.resizer }}
          resources:
{{ toYaml .Values.resources.resizer | indent 12 }}
{{- end }}
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          {{- if .Values.global.useTokenRequestor }}
          - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
            name: kubeconfig-csi-resizer
            readOnly: true
          {{- else }}
          - name: csi-resizer
            mountPath: /var/lib/csi-resizer
          {{- end }}
{{- end }}
        - name: ionos-csi-controller
          image: {{ index .Values.images "csi-driver-controller" }}
          env:
          - name: KUBECONFIG
          {{- if .Values.global.useTokenRequestor }}
            value: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
          {{- else }}
            value: /var/lib/ionos-csi-controller/kubeconfig
          {{- end }}
          - name: CSI_ENDPOINT
            value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          - name: IE_DRIVER_NAME
            value: cloud.ionos.com
          - name: IE_DRIVER_MODE
            value: ControllerServer
          - name: LOGGER_LEVEL
            value: "{{ .Values.loggerLevel }}" # Options: DEVELOPMENT, PRODUCTION
{{- if .Values.resources.controller }}
          resources:
{{ toYaml .Values.resources.controller | indent 12 }}
{{- end }}
          volumeMounts:
          - mountPath: /var/lib/csi/sockets/pluginproxy/
            name: socket-dir
          - name: ionos-csi-controller
            mountPath: /var/lib/ionos-csi-controller
          - mountPath: /etc/ie-csi
            name: ie-csi-dir
            readOnly: true
          - mountPath: /etc/ie-csi/clouds
            name: clouds-dir
            readOnly: true
        - name: csi-provisioner
          image: {{ index .Values.images "csi-provisioner" }}
          args:
          - "--timeout=300s"
          - "--csi-address=$(ADDRESS)"
          - "--feature-gates=Topology=true"
          - "--strict-topology"
          {{- if .Values.global.useTokenRequestor }}
          - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
          {{- else }}
          - --kubeconfig=/var/lib/csi-provisioner/kubeconfig
          {{- end }}
          - "--leader-election"
          - "--leader-election-namespace=$(CSI_NAMESPACE)"
          env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: CSI_NAMESPACE
            value: kube-system
{{- if .Values.resources.provisioner }}
          resources:
{{ toYaml .Values.resources.provisioner | indent 12 }}
{{- end }}
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          {{- if .Values.global.useTokenRequestor }}
          - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
            name: kubeconfig-csi-provisioner
            readOnly: true
          {{- else }}
          - name: csi-provisioner
            mountPath: /var/lib/csi-provisioner
          {{- end }}
      volumes:
      {{- if .Values.global.useTokenRequestor }}
      - name: kubeconfig-csi-attacher
        projected:
          defaultMode: 420
          sources:
            - secret:
                items:
                  - key: kubeconfig
                    path: kubeconfig
                name: generic-token-kubeconfig
                optional: false
            - secret:
                items:
                  - key: token
                    path: token
                name: shoot-access-csi-attacher
                optional: false
      - name: kubeconfig-csi-resizer
        projected:
          defaultMode: 420
          sources:
            - secret:
                items:
                  - key: kubeconfig
                    path: kubeconfig
                name: generic-token-kubeconfig
                optional: false
            - secret:
                items:
                  - key: token
                    path: token
                name: shoot-access-csi-resizer
                optional: false
      - name: kubeconfig-csi-provisioner
        projected:
          defaultMode: 420
          sources:
            - secret:
                items:
                  - key: kubeconfig
                    path: kubeconfig
                name: generic-token-kubeconfig
                optional: false
            - secret:
                items:
                  - key: token
                    path: token
                name: shoot-access-csi-provisioner
                optional: false
      - name: kubeconfig-csi-driver
        projected:
          defaultMode: 420
          sources:
            - secret:
                items:
                  - key: kubeconfig
                    path: kubeconfig
                name: generic-token-kubeconfig
                optional: false
            - secret:
                items:
                  - key: token
                    path: token
                name: shoot-access-ionos-csi-controller
                optional: false
      {{- else }}
      - name: ionos-csi-controller
        secret:
          secretName: ionos-csi-controller
      - name: csi-attacher
        secret:
          secretName: csi-attacher
      - name: csi-provisioner
        secret:
          secretName: csi-provisioner
      - name: csi-resizer
        secret:
          secretName: csi-resizer
      {{- end }}
      - name: socket-dir
        emptyDir: {}
      - name: ie-csi-dir
        secret:
          secretName: ionos-csi
          items:
          - key: ionosCfg
            path: "cfg.json"
      - name: clouds-dir
        secret:
          secretName: ionos-csi
          items:
          - key: ionosCloudsConf
            path: {{ .Values.csiDatacenterID | quote }}
