apiVersion: v1
kind: Secret
metadata:
  name: ionos-csi
  namespace: {{ .Release.Namespace }}
stringData:
  ionosCfg: |-
    {"datacenter-id": {{ .Values.csiDatacenterID | quote }}}
  ionosCloudsConf: |-
    {"username": {{ .Values.user | quote }}, "password": {{ .Values.password | quote }}}'"}


