apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret-gardener-extension-admission-ionos-cert: {{ include (print $.Template.BasePath "/secret-cert.yaml") . | sha256sum }}
        {{- if .Values.global.kubeconfig }}
        checksum/gardener-extension-admission-ionos-kubeconfig: {{ include (print $.Template.BasePath "/secret-kubeconfig.yaml") . | sha256sum }}
        {{- end }}
      labels:
{{ include "labels" . | indent 8 }}
    spec:
      {{- if or (not .Values.global.virtualGarden.enabled) (and (.Values.global.virtualGarden.enabled) (.Values.global.virtualGarden.user.name) (.Values.global.serviceAccountTokenVolumeProjection.enabled)) }}
      serviceAccountName: {{ include "name" . }}
      {{- end }}
      {{- if .Values.global.kubeconfig }}
      automountServiceAccountToken: false
      {{- end }}
      containers:
      - name: {{ include "name" . }}
        image: {{ include "image" .Values.global.image }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - /gardener-extension-admission-ionos
        - --webhook-config-server-port={{ .Values.global.webhookConfig.serverPort }}
        - --webhook-config-cert-dir=/etc/gardener-extension-admission-ionos/srv
        {{- if .Values.global.kubeconfig }}
        - --kubeconfig=/etc/gardener-extension-admission-ionos/kubeconfig/kubeconfig
        {{- end }}
        {{- if .Values.healthPort }}
        - --health-bind-address=:{{ .Values.healthPort }}
        {{- end }}
        ports:
        - name: webhook-server
          containerPort: {{ .Values.global.webhookConfig.serverPort }}
          protocol: TCP
        {{- if .Values.healthPort }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        {{- end }}
{{- if .Values.global.resources }}
        resources:
{{ toYaml .Values.global.resources | nindent 10 }}
{{- end }}
        volumeMounts:
        - name: gardener-extension-admission-ionos-cert
          mountPath: /etc/gardener-extension-admission-ionos/srv
          readOnly: true
        {{- if .Values.global.kubeconfig }}
        - name: gardener-extension-admission-ionos-kubeconfig
          mountPath: /etc/gardener-extension-admission-ionos/kubeconfig
          readOnly: true
        {{- end }}
        {{- if .Values.global.serviceAccountTokenVolumeProjection.enabled }}
        - name: service-account-token
          mountPath: /var/run/secrets/projected/serviceaccount
          readOnly: true
        {{- end }}
      volumes:
      - name: gardener-extension-admission-ionos-cert
        secret:
          secretName: gardener-extension-admission-ionos-cert
          defaultMode: 420
      {{- if .Values.global.kubeconfig }}
      - name: gardener-extension-admission-ionos-kubeconfig
        secret:
          secretName: gardener-extension-admission-ionos-kubeconfig
          defaultMode: 420
      {{- end }}
      {{- if .Values.global.serviceAccountTokenVolumeProjection.enabled }}
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: {{ .Values.global.serviceAccountTokenVolumeProjection.expirationSeconds }}
              {{- if .Values.global.serviceAccountTokenVolumeProjection.audience }}
              audience: {{ .Values.global.serviceAccountTokenVolumeProjection.audience }}
              {{- end }}
      {{- end }}
